SELECT DISTINCT STATE, CITY, ZIP FROM CUSTOMER;

SELECT EMPNAME, DEPARTMENT, PHONE, EMAIL FROM EMPLOYEE WHERE PHONE LIKE '3%';

SELECT * FROM RESOURCETBL WHERE RATE BETWEEN 10 AND 20 ORDER BY RATE;

SELECT EVENTNO, DATEAUTH, STATUS FROM EVENTREQUEST WHERE (STATUS = 'Approved' OR STATUS = 'Denied') AND (DATEAUTH BETWEEN '1-July-2013' AND '31-July-2013');

SELECT LOCNO, LOCNAME FROM FACILITY INNER JOIN LOCATION ON FACILITY.FACNO = LOCATION.FACNO
WHERE FACNAME = 'Basketball arena';

SELECT PLANNO, COUNT(PLANNO) AS LINES, SUM(NUMBERFLD) AS RESOURCES FROM EVENTPLANLINE 
GROUP BY PLANNO
HAVING COUNT(PLANNO) >= 1;