SELECT ER.EVENTNO, ER.DATEHELD, COUNT(EP.PLANNO)
FROM EVENTREQUEST ER, EVENTPLAN EP
WHERE ER.EVENTNO = EP.EVENTNO
AND EP.WORKDATE BETWEEN '1-Dec-2013' AND '31-Dec-2013'
GROUP BY EP.EVENTNO, ER.DATEHELD, ER.EVENTNO
HAVING COUNT(EP.PLANNO) > 1;

SELECT EP.PLANNO, EP.EVENTNO, EP.WORKDATE, EP.ACTIVITY
FROM EVENTPLAN EP,EVENTREQUEST ER, FACILITY FAC
WHERE EP.EVENTNO = ER.EVENTNO
AND ER.FACNO = FAC.FACNO
AND FAC.FACNAME = 'Basketball arena'
AND EP.WORKDATE BETWEEN '1-Dec-2013' AND '31-Dec-2013'; 

SELECT ER.EVENTNO, ER.DATEHELD, ER.STATUS, ER.ESTCOST
FROM EVENTREQUEST ER, EVENTPLAN EP, EMPLOYEE EMP, FACILITY FAC 
WHERE ER.FACNO = FAC.FACNO
AND ER.EVENTNO = EP.EVENTNO
AND EP.EMPNO = EMP.EMPNO
AND FAC.FACNAME = 'Basketball arena'
AND ER.DATEHELD BETWEEN '1-Oct-2013' AND '31-Dec-2013';

SELECT EPL.PLANNO, EPL.LINENO, RES.RESNAME, EPL.NUMBERFLD, LOC.LOCNAME, EPL.TIMESTART, EPL.TIMEEND
FROM EVENTPLAN EP, LOCATION LOC, RESOURCETBL RES, EVENTPLANLINE EPL, FACILITY FAC
WHERE EPL.PLANNO = EP.PLANNO
AND EPL.LOCNO = LOC.LOCNO
AND EPL.RESNO = RES.RESNO
AND LOC.FACNO = FAC.FACNO
AND FAC.FACNAME = 'Basketball arena'
AND EP.ACTIVITY = 'Operation'
AND EP.WORKDATE BETWEEN '1-Oct-2013' AND '31-Dec-2013';

INSERT INTO FACILITY VALUES ('F104','Swimming Pool');

INSERT INTO LOCATION VALUES ('L107','F104','Door');

INSERT INTO LOCATION VALUES ('L108','F104','Locker Room');

UPDATE TABLE LOCATION 
SET LOCNAME = 'Gate'
WHERE LOCNAME = 'Door'; 

DELETE FROM LOCATION WHERE LOCNAME = 'Locker Room';
